//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.13 at 02:47:06 PM IST 
//


package com.greenfield.nexux_client;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SearchNGResponse_QNAME = new QName("", "searchNGResponse");
    private final static QName _SearchResults_QNAME = new QName("", "search-results");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NexusNGArtifact }
     * 
     */
    public NexusNGArtifact createNexusNGArtifact() {
        return new NexusNGArtifact();
    }

    /**
     * Create an instance of {@link ArtifactHit }
     * 
     */
    public ArtifactHit createArtifactHit() {
        return new ArtifactHit();
    }

    /**
     * Create an instance of {@link SearchResponse }
     * 
     */
    public SearchResponse createSearchResponse() {
        return new SearchResponse();
    }

    /**
     * Create an instance of {@link SearchNGResponse }
     * 
     */
    public SearchNGResponse createSearchNGResponse() {
        return new SearchNGResponse();
    }

    /**
     * Create an instance of {@link NexusArtifact }
     * 
     */
    public NexusArtifact createNexusArtifact() {
        return new NexusArtifact();
    }

    /**
     * Create an instance of {@link ArtifactLink }
     * 
     */
    public ArtifactLink createArtifactLink() {
        return new ArtifactLink();
    }

    /**
     * Create an instance of {@link NexusResponse }
     * 
     */
    public NexusResponse createNexusResponse() {
        return new NexusResponse();
    }

    /**
     * Create an instance of {@link NexusIndexerResponse }
     * 
     */
    public NexusIndexerResponse createNexusIndexerResponse() {
        return new NexusIndexerResponse();
    }

    /**
     * Create an instance of {@link RepositoryDetail }
     * 
     */
    public RepositoryDetail createRepositoryDetail() {
        return new RepositoryDetail();
    }

    /**
     * Create an instance of {@link NexusNGArtifact.ArtifactHits }
     * 
     */
    public NexusNGArtifact.ArtifactHits createNexusNGArtifactArtifactHits() {
        return new NexusNGArtifact.ArtifactHits();
    }

    /**
     * Create an instance of {@link ArtifactHit.ArtifactLinks }
     * 
     */
    public ArtifactHit.ArtifactLinks createArtifactHitArtifactLinks() {
        return new ArtifactHit.ArtifactLinks();
    }

    /**
     * Create an instance of {@link SearchResponse.Data }
     * 
     */
    public SearchResponse.Data createSearchResponseData() {
        return new SearchResponse.Data();
    }

    /**
     * Create an instance of {@link SearchNGResponse.Data }
     * 
     */
    public SearchNGResponse.Data createSearchNGResponseData() {
        return new SearchNGResponse.Data();
    }

    /**
     * Create an instance of {@link SearchNGResponse.RepoDetails }
     * 
     */
    public SearchNGResponse.RepoDetails createSearchNGResponseRepoDetails() {
        return new SearchNGResponse.RepoDetails();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchNGResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "searchNGResponse")
    public JAXBElement<SearchNGResponse> createSearchNGResponse(SearchNGResponse value) {
        return new JAXBElement<SearchNGResponse>(_SearchNGResponse_QNAME, SearchNGResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "search-results")
    public JAXBElement<SearchResponse> createSearchResults(SearchResponse value) {
        return new JAXBElement<SearchResponse>(_SearchResults_QNAME, SearchResponse.class, null, value);
    }

}
