//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.13 at 02:47:06 PM IST 
//


package com.greenfield.nexux_client;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for searchNGResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="searchNGResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{}nexusIndexerResponse">
 *       &lt;sequence>
 *         &lt;element name="tooManyResults" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="data" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="nexusNGArtifact" type="{}nexusNGArtifact" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="count" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="collapsed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="repoDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="repositoryDetail" type="{}repositoryDetail" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="totalCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "searchNGResponse", propOrder = {
    "tooManyResults",
    "data",
    "count",
    "collapsed",
    "repoDetails",
    "totalCount",
    "from"
})
public class SearchNGResponse
    extends NexusIndexerResponse
{

    protected boolean tooManyResults;
    protected SearchNGResponse.Data data;
    protected int count;
    protected boolean collapsed;
    protected SearchNGResponse.RepoDetails repoDetails;
    protected int totalCount;
    protected int from;

    /**
     * Gets the value of the tooManyResults property.
     * 
     */
    public boolean isTooManyResults() {
        return tooManyResults;
    }

    /**
     * Sets the value of the tooManyResults property.
     * 
     */
    public void setTooManyResults(boolean value) {
        this.tooManyResults = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link SearchNGResponse.Data }
     *     
     */
    public SearchNGResponse.Data getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchNGResponse.Data }
     *     
     */
    public void setData(SearchNGResponse.Data value) {
        this.data = value;
    }

    /**
     * Gets the value of the count property.
     * 
     */
    public int getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     */
    public void setCount(int value) {
        this.count = value;
    }

    /**
     * Gets the value of the collapsed property.
     * 
     */
    public boolean isCollapsed() {
        return collapsed;
    }

    /**
     * Sets the value of the collapsed property.
     * 
     */
    public void setCollapsed(boolean value) {
        this.collapsed = value;
    }

    /**
     * Gets the value of the repoDetails property.
     * 
     * @return
     *     possible object is
     *     {@link SearchNGResponse.RepoDetails }
     *     
     */
    public SearchNGResponse.RepoDetails getRepoDetails() {
        return repoDetails;
    }

    /**
     * Sets the value of the repoDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchNGResponse.RepoDetails }
     *     
     */
    public void setRepoDetails(SearchNGResponse.RepoDetails value) {
        this.repoDetails = value;
    }

    /**
     * Gets the value of the totalCount property.
     * 
     */
    public int getTotalCount() {
        return totalCount;
    }

    /**
     * Sets the value of the totalCount property.
     * 
     */
    public void setTotalCount(int value) {
        this.totalCount = value;
    }

    /**
     * Gets the value of the from property.
     * 
     */
    public int getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     */
    public void setFrom(int value) {
        this.from = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="nexusNGArtifact" type="{}nexusNGArtifact" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nexusNGArtifact"
    })
    public static class Data {

        protected List<NexusNGArtifact> nexusNGArtifact;

        /**
         * Gets the value of the nexusNGArtifact property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the nexusNGArtifact property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNexusNGArtifact().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link NexusNGArtifact }
         * 
         * 
         */
        public List<NexusNGArtifact> getNexusNGArtifact() {
            if (nexusNGArtifact == null) {
                nexusNGArtifact = new ArrayList<NexusNGArtifact>();
            }
            return this.nexusNGArtifact;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="repositoryDetail" type="{}repositoryDetail" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "repositoryDetail"
    })
    public static class RepoDetails {

        protected List<RepositoryDetail> repositoryDetail;

        /**
         * Gets the value of the repositoryDetail property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the repositoryDetail property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRepositoryDetail().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RepositoryDetail }
         * 
         * 
         */
        public List<RepositoryDetail> getRepositoryDetail() {
            if (repositoryDetail == null) {
                repositoryDetail = new ArrayList<RepositoryDetail>();
            }
            return this.repositoryDetail;
        }

    }

}
